[DATABASE]
url=${DATABASE_URL}

[SECURITY]
secret_key=${SECRET_KEY}
algorithm=${ALGORITHM}
access_token_expire_minutes=${ACCESS_TOKEN_EXPIRE_MINUTES}

[CLUB]
name=${CLUB_NAME}
frontend_url=${FRONTEND_URL}

[ANNUAL_FEE]
amount=${ANNUAL_FEE_AMOUNT}
period_type=${PERIOD_TYPE}
prorrate_type=${PRORRATE_TYPE}

[ADMIN]
username=${ADMIN_USERNAME}
email=${ADMIN_EMAIL}
password=${ADMIN_PASSWORD}

[WIZARD]
# Desactivar el wizard de inicialización (true/false o cualquier valor para desactivar)
disable_wizard=${DISABLE_WIZARD}

